image: bradrydzewski/node:0.10

script:
  - npm install --quiet -g grunt-cli karma bower phantomjs
  - npm install --quiet
  - bower install
  - grunt setup
  - npm test

deploy:
  bash:
    command: grunt compile
