image: bradrydzewski/node0.10

script:
  - sudo apt-get -y install build-essential
  - sudo apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
  - sudo add-apt-repository ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install -y python2.7
  - npm install -g grunt grunt-cli karma-cli karma bower
  - npm install
  - bower install
  - grunt
